Adjust DynamicListForm.itemcomponent
https://github.com/cockpit-project/cockpit/pull/21569 cleaned up the API
to get a component type instead of a (degenerate) instance. This fixes
most type check errors like

> src/ImageRunModal.jsx(1062,51): error TS2740:
> Type '{}' is missing the following properties from type '{ id: any; item: any; ...