package.json: Pin down terser 3.14.1
The recent terser 3.16.0 release causes the build to break with

    TypeError: Cannot read property 'minify' of undefined

(https://github.com/terser-js/terser/issues/251)

Until this is fixed, pin down the version of terser to the previous
known version 3.14.1.

Same as the workaround for Cockpit by Martin Pitt:

https://github.com/cockpit-project/cockpit/pull/11105