Declare type of `partitionedContainers`
Add an explicit type so that tsc does not infer that `no-pod` is a
required property. This led to

> src/Containers.jsx(668,24): error TS2790: The operand of a 'delete' operator must be optional.

Declaring it explicitly states that all keys are optional.