npm: Avoid broken eslint-plugin-jsx-a11y 6.5.0 version
That latest version has a grave regression:

    TypeError: Error while loading rule 'jsx-a11y/alt-text': rule.create is not a function

Downgrade back to 6.4.1 for the time being.

See https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/824