test: wait for CPU to settle before fetching memory
On the OpenSuse Tumbleweed image the CPU usage influences the amount of
memory used and causes the test to flake with:

```
AssertionError: 381.0 not less than or equal to 300.0
```

Waiting for the CPU to settle also stabilises the memory usage.